import eslint from '@eslint/js';
import { defineConfig } from 'eslint/config';
import antiTrojanSourcePlugin from 'eslint-plugin-anti-trojan-source';
import importPlugin from 'eslint-plugin-import';
import prettierPluginRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
	{
		name: 'teams-bridge/linter',
		linterOptions: {
			reportUnusedDisableDirectives: true,
		},
	},
	{
		name: 'teams-bridge/ignored',
		ignores: ['**/dist', '**/coverage', 'eslint.config.mjs'],
	},
	eslint.configs.recommended,
	tseslint.configs.recommendedTypeChecked,
	{
		languageOptions: {
			parserOptions: {
				projectService: true,
			},
		},
	},
	importPlugin.flatConfigs.recommended,
	importPlugin.flatConfigs.typescript,
	{
		name: 'teams-bridge/anti-trojan',
		plugins: {
			'anti-trojan-source': antiTrojanSourcePlugin,
		},
		rules: {
			'anti-trojan-source/no-bidi': 'error',
		},
	},
	prettierPluginRecommended,
	{
		name: 'teams-bridge/ecmascript',
		languageOptions: {
			ecmaVersion: 2024,
			sourceType: 'module',
			globals: {
				...globals.node,
			},
		},
	},
	{
		name: 'teams-bridge/best-practices',
		rules: {
			'array-callback-return': ['error', { allowImplicit: true }],
			'block-scoped-var': 'error',
			complexity: ['warn', 31],
			'dot-notation': ['error', { allowKeywords: true }],
			eqeqeq: ['error', 'allow-null'],
			'guard-for-in': 'error',
			'no-caller': 'error',
			'no-else-return': ['error', { allowElseIf: false }],
			'no-empty-function': ['error', { allow: ['arrowFunctions', 'functions', 'methods'] }],
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-extra-label': 'error',
			'no-implied-eval': 'error',
			'no-iterator': 'error',
			'no-lone-blocks': 'error',
			'no-loop-func': 'error',
			'no-multi-str': 'error',
			'no-new-wrappers': 'error',
			'no-proto': 'error',
			'no-return-assign': ['error', 'always'],
			'no-return-await': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-throw-literal': 'error',
			'no-useless-catch': 'warn',
			'no-useless-concat': 'off',
			'no-useless-return': 'error',
			yoda: 'error',
		},
	},
	{
		name: 'teams-bridge/common-mistakes',
		rules: {
			'getter-return': ['error', { allowImplicit: true }],
			'no-async-promise-executor': 'warn',
			'no-case-declarations': 'warn',
			'no-constant-binary-expression': 'warn',
			'no-debugger': 'error',
			'no-inner-declarations': ['error', 'functions'],
			'no-prototype-builtins': 'warn',
			'no-unsafe-optional-chaining': 'warn',
			'valid-typeof': ['error', { requireStringLiterals: true }],
		},
	},
	{
		name: 'teams-bridge/stylistic',
		rules: {
			'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: false }],
			'new-cap': 'off',
			'no-array-constructor': 'error',
			'no-lonely-if': 'error',
			'no-multi-assign': 'error',
			'no-nested-ternary': 'error',
			'no-unneeded-ternary': ['error', { defaultAssignment: false }],
			'no-useless-escape': 'off',
			'one-var': ['error', 'never'],
			'operator-assignment': ['error', 'always'],
		},
	},
	{
		name: 'teams-bridge/variables',
		rules: {
			'no-unused-vars': ['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true, caughtErrors: 'none' }],
			'no-use-before-define': ['error', { functions: true, classes: true, variables: true }],
		},
	},
	{
		name: 'teams-bridge/es2015',
		rules: {
			'no-duplicate-imports': 'off',
			'no-useless-computed-key': 'error',
			'no-useless-constructor': 'error',
			'no-useless-rename': ['error', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
			'no-var': 'error',
			'object-shorthand': 'error',
			'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: true }],
			'prefer-rest-params': 'error',
			'prefer-template': 'error',
		},
	},
	{
		name: 'teams-bridge/import',
		settings: {
			'import/resolver': {
				node: true,
				typescript: true,
			},
		},
		rules: {
			'import/no-unresolved': ['error', { commonjs: true, caseSensitive: true }],
			'import/named': 'off',
			'import/default': 'off',
			'import/namespace': 'off',
			'import/export': 'error',
			'import/no-named-as-default': 'off',
			'import/no-named-as-default-member': 'off',
			'import/first': 'error',
			'import/no-duplicates': 'error',
			'import/order': [
				'error',
				{
					'newlines-between': 'always',
					groups: ['builtin', ['external', 'internal'], ['parent', 'sibling', 'index']],
					alphabetize: { order: 'asc' },
				},
			],
			'import/newline-after-import': 'error',
			'import/no-absolute-path': 'error',
			'import/no-dynamic-require': 'error',
			'import/no-self-import': 'error',
			'import/no-useless-path-segments': 'error',
		},
	},
	{
		name: 'teams-bridge/typescript',
		files: ['**/*.@(ts|cts|mts)'],
		rules: {
			'@typescript-eslint/ban-ts-comment': 'warn',
			'@typescript-eslint/consistent-type-exports': 'error',
			'@typescript-eslint/consistent-type-imports': ['error', { disallowTypeAnnotations: false }],
			'@typescript-eslint/naming-convention': [
				'error',
				{ selector: 'variableLike', format: ['camelCase'], leadingUnderscore: 'allow' },
				{ selector: ['variable'], format: ['camelCase', 'UPPER_CASE', 'PascalCase'], leadingUnderscore: 'allowSingleOrDouble' },
				{ selector: 'function', format: ['camelCase', 'PascalCase'], leadingUnderscore: 'allowSingleOrDouble' },
				{ selector: 'interface', format: ['PascalCase'] },
			],
			'@typescript-eslint/await-thenable': 'warn',
			'@typescript-eslint/no-array-delete': 'warn',
			'@typescript-eslint/no-base-to-string': 'warn',
			'@typescript-eslint/no-dupe-class-members': 'error',
			'@typescript-eslint/no-duplicate-enum-values': 'warn',
			'@typescript-eslint/no-duplicate-type-constituents': 'warn',
			'@typescript-eslint/no-empty-function': 'error',
			'@typescript-eslint/no-empty-interface': 'warn',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-for-in-array': 'warn',
			'@typescript-eslint/no-implied-eval': 'warn',
			'@typescript-eslint/no-non-null-assertion': 'warn',
			'@typescript-eslint/no-redeclare': 'error',
			'@typescript-eslint/no-require-imports': 'warn',
			'@typescript-eslint/no-this-alias': 'error',
			'@typescript-eslint/no-unnecessary-type-assertion': 'warn',
			'@typescript-eslint/no-unused-expressions': 'warn',
			'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', ignoreRestSiblings: true, caughtErrors: 'none' }],
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-declaration-merging': 'warn',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-enum-comparison': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			'@typescript-eslint/only-throw-error': 'warn',
			'@typescript-eslint/prefer-promise-reject-errors': 'warn',
			'@typescript-eslint/prefer-optional-chain': 'warn',
			'@typescript-eslint/restrict-plus-operands': 'warn',
			'@typescript-eslint/restrict-template-expressions': 'warn',
			'no-dupe-class-members': 'off',
			'no-empty-function': 'off',
			'no-redeclare': 'off',
			'no-undef': 'off',
			'no-unused-vars': 'off',
			'no-use-before-define': 'off',
			'no-useless-constructor': 'off',
		},
	},
);
