name: Pull Request Build

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(fromJSON('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.pull_request.author_association) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build'))

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.16.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Install Rocket.Chat Apps CLI
        run: npm install -g @rocket.chat/apps-cli@1.13.0

      - name: Build App
        run: rc-apps package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: teams-bridge-app
          path: dist/*.zip
          if-no-files-found: error
